### ISSUE TITLE
Create plugin standard

### ISSUE THREAD

**Issue by LNow** [syvita/dao#26]
**Is your feature request related to a problem? Please describe.**
In order to implement plugins system we need a plugin-trait contract that defines set of public functions all plugins must expose.

**Describe the solution you'd like**
Trait with 2 functions:

- `get-name` returns plugin name
- `get-version` returns plugin version

**Additional context**
Discussion can about plugins, how they should work and communicate with each other can be found here: https://github.com/labs3/daoOS/discussions/24

**Comment by JMKJR** [comment]
I'd like to think on this more as a result of our convo in #24 . Would be nice to have an updated C4 of communication between RBAC, SCPS, and Treasury(Vault) before diving into implementation level details. Do you agree? I can provide a new C4 with our updated understanding this weekend. As of right now I don't have a perfect perspective on how all of the pieces fit together to know whether or not the solution proposed in this issue is the best approach.

**Comment by LNow** [comment]
OK, lets update our models first.

**Comment by cryptopanter** [comment]
> **Is your feature request related to a problem? Please describe.**
> In order to implement plugins system we need a plugin-trait contract that defines set of public functions all plugins must expose.
> 
> **Describe the solution you'd like**
> Trait with 2 functions:
> 
> * `get-name` returns plugin name
> * `get-version` returns plugin version
> 
> **Additional context**
> Discussion can about plugins, how they should work and communicate with each other can be found here: #24

This is goung to be a kind of standard for writing plugin contracts?

**Comment by LNow** [comment]
> This is goung to be a kind of standard for writing plugin contracts?

Yes it should be viewed as standard minimal set of functions that every single plugin must implement.

**Comment by cryptopanter** [comment]
> > This is goung to be a kind of standard for writing plugin contracts?
> 
> Yes it should be viewed as standard minimal set of functions that every single plugin must implement.
Ok then we should set its standard identifier... Syv-04
